#!/usr/bin/env python3
"""Run all 5 deployment gates and produce a ship/no-ship report.

MGMT655 Dimension A evidence — explicit production-readiness judgment.
Run from repo root: uv run python scripts/run_deployment_gate.py
"""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JOURNAL_DIR = ROOT / "journal"
sys.path.insert(0, str(ROOT / "src"))

from greenloop.governance.deployment_gate import (
    DeploymentDecision,
    GateResult,
    GateStatus,
    evaluate_all_gates,
)


def _gate_status_icon(status: GateStatus) -> str:
    return {
        "PASS": "✅",
        "FAIL": "❌",
        "CONDITIONAL": "⚠️",
        "PENDING": "⏳",
    }[status.value]


def _print_gate(gate: GateResult) -> None:
    icon = _gate_status_icon(gate.status)
    print(f"\n{'─' * 60}")
    print(f"  Gate {gate.number}: {gate.name} [{icon} {gate.status.value}]")
    print(f"{'─' * 60}")
    for cr in gate.criteria:
        cicon = _gate_status_icon(cr.status)
        print(f"  {cicon} {cr.name}: {cr.message}")
        if cr.details:
            print(f"     └─ {cr.details}")


def _render_markdown_report(decision: DeploymentDecision) -> str:
    today = date.today().isoformat()
    lines = [
        f"# GreenLoop F2C — Deployment Gate Decision",
        f"",
        f"**Date:** {today}",
        f"**Phase:** Phase 0 Complete → Phase 1 Pilot Proposal",
        f"",
        f"## Ship Decision: **{decision.overall_status.value}**",
        f"",
        f"{decision.overall_message}",
        f"",
    ]

    if decision.restrictions:
        lines.append(f"**Restriction:** {decision.restrictions}")
        lines.append("")

    if decision.upgrade_conditions:
        lines.append("**Upgrade conditions for GA (General Availability):**")
        for cond in decision.upgrade_conditions:
            lines.append(f"- {cond}")
        lines.append("")

    lines.append("## Gate Results")
    lines.append("")
    lines.append("| Gate | Name | Status | Evidence |")
    lines.append("|------|------|--------|----------|")

    for gate in decision.gate_results:
        icon = _gate_status_icon(gate.status)
        evidence = "; ".join(
            f"{cr.name}: {cr.message.split('(')[0].strip()}"
            for cr in gate.criteria[:2]
        )
        lines.append(f"| {gate.number} | {gate.name} | {icon} {gate.status.value} | {evidence} |")

    lines.append("")
    lines.append("## Detailed Criteria")
    lines.append("")

    for gate in decision.gate_results:
        icon = _gate_status_icon(gate.status)
        lines.append(f"### Gate {gate.number}: {gate.name} [{icon} {gate.status.value}]")
        lines.append("")
        for cr in gate.criteria:
            cicon = _gate_status_icon(cr.status)
            lines.append(f"**{cicon} {cr.name}** — {cr.message}")
            if cr.details:
                lines.append(f"   - Details: {cr.details}")
            lines.append("")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by Phase 8 Deployment Gate — MGMT655 Dimension A*")

    return "\n".join(lines)


def _render_console_report(decision: DeploymentDecision) -> None:
    print(f"\n{'═' * 62}")
    print(f"  GREENLOOP F2C — DEPLOYMENT GATE EVALUATION")
    print(f"  Date: {decision.evaluated_at}")
    print(f"{'═' * 62}")

    for gate in decision.gate_results:
        _print_gate(gate)

    print(f"\n{'═' * 62}")
    icon = _gate_status_icon(decision.overall_status)
    print(f"  OVERALL: [{icon}] {decision.overall_status.value}")
    print(f"  {decision.overall_message}")
    if decision.restrictions:
        print(f"  RESTRICTION: {decision.restrictions}")
    if decision.upgrade_conditions:
        print(f"  UPGRADE CONDITIONS:")
        for cond in decision.upgrade_conditions:
            print(f"    → {cond}")
    print(f"{'═' * 62}")


def run_all_gates() -> DeploymentDecision:
    """Evaluate all 5 gates, save reports, print console output."""
    print("Evaluating deployment gates...")

    decision = evaluate_all_gates()
    _render_console_report(decision)

    # Save JSON
    json_path = JOURNAL_DIR / f"deployment-gate-{decision.evaluated_at}.json"
    json_data = {
        "evaluated_at": decision.evaluated_at,
        "overall_status": decision.overall_status.value,
        "overall_message": decision.overall_message,
        "ship_recommended": decision.ship_recommended,
        "restrictions": decision.restrictions,
        "upgrade_conditions": decision.upgrade_conditions,
        "gates": [
            {
                "number": g.number,
                "name": g.name,
                "status": g.status.value,
                "criteria": [
                    {
                        "name": cr.name,
                        "status": cr.status.value,
                        "message": cr.message,
                        "details": cr.details,
                    }
                    for cr in g.criteria
                ],
            }
            for g in decision.gate_results
        ],
    }
    json_path.write_text(json.dumps(json_data, indent=2))
    print(f"\n📄 JSON report saved: {json_path}")

    # Save markdown
    md_path = JOURNAL_DIR / f"deployment-gate-{decision.evaluated_at}.md"
    md_path.write_text(_render_markdown_report(decision))
    print(f"📄 Markdown report saved: {md_path}")

    # Always save as deployment-gate-decision.md (overwrite)
    decision_md = JOURNAL_DIR / "deployment-gate-decision.md"
    decision_md.write_text(_render_markdown_report(decision))
    print(f"📄 Decision doc saved: {decision_md}")

    return decision


if __name__ == "__main__":
    decision = run_all_gates()
    # Exit code: 0 if ship recommended, 1 if not
    sys.exit(0 if decision.ship_recommended else 1)
