"""Layer 1b training script — EfficientNet-B0 dual-head transfer learning.

Trains the model described in specs/layer1b_cv_diagnosis.md §2 on synthetic
images generated by data_pipeline.py.

Usage:
    python -m adoptakale.layer1b.train [--data-dir data/cv_training] [--epochs 30]
                                     [--checkpoint models/transfer_learning_v1.pt]

The trained checkpoint is loaded automatically by inference.load_cv_model() when
GREENLOOP_CV_MODE=real (or when the dashboard starts without GREENLOOP_CV_MODE set).
"""

from __future__ import annotations

import argparse
import logging
import time
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from PIL import Image
from torch.utils.data import DataLoader, Dataset, TensorDataset
from torchvision import transforms

from adoptakale.layer1b.architecture import (
    DualHeadClassifier,
    DiagnosisResult,
    GROWTH_LABELS,
    NUTRITION_LABELS,
)
from adoptakale.layer1b.data_pipeline import generate_training_data, load_training_data
from adoptakale.utils.config import MODELS_DIR

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Hyperparameters (spec §3 — frozen backbone for MVP)
# ---------------------------------------------------------------------------

DEFAULT_EPOCHS = 30
DEFAULT_BATCH_SIZE = 16
DEFAULT_LR = 1e-3
IMAGE_SIZE = 224

# Class weights — per spec §2.3: class-weighted loss if imbalance > 3:1
# Synthetic data is balanced (20 images per cell), so use uniform weights.
GROWTH_LOSS_WEIGHT = 1.0
NUTRITION_LOSS_WEIGHT = 1.0


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------


class SyntheticCVDataset(Dataset):
    """Loads synthetic images from the generated training directory."""

    def __init__(self, manifest: dict, split: str = "train", train_fraction: float = 0.8):
        self.samples: list[tuple[str, int, int]] = []  # (filepath, growth_idx, nutrition_idx)

        for crop, stages in manifest.items():
            for stage, nutrition_map in stages.items():
                for nutrition, image_ids in nutrition_map.items():
                    growth_idx = GROWTH_LABELS.index(stage)
                    nutrition_idx = NUTRITION_LABELS.index(nutrition)
                    for img_id, filepath in image_ids.items():
                        self.samples.append((filepath, growth_idx, nutrition_idx))

        # Deterministic split using sample count as seed
        n = len(self.samples)
        n_train = int(n * train_fraction)
        rng = torch.Generator().manual_seed(42)
        indices = torch.randperm(n, generator=rng).tolist()
        chosen = indices[:n_train] if split == "train" else indices[n_train:]
        self.samples = [self.samples[i] for i in chosen]

        self.transform = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.229, 0.224]),
        ])

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int):
        filepath, growth_idx, nutrition_idx = self.samples[idx]
        img = Image.open(filepath).convert("RGB")
        img = self.transform(img)
        return img, growth_idx, nutrition_idx


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------


def train_epoch(
    model: nn.Module,
    loader: DataLoader,
    optimizer: optim.Optimizer,
    device: torch.device,
) -> dict[str, float]:
    model.train()
    total_loss = 0.0
    n_batches = 0
    growth_correct = 0
    nutrition_correct = 0
    total = 0

    loss_fn = nn.CrossEntropyLoss()

    for batch in loader:
        images, growth_labels, nutrition_labels = batch
        images = images.to(device)
        growth_labels = growth_labels.to(device)
        nutrition_labels = nutrition_labels.to(device)

        optimizer.zero_grad()
        logits_growth, logits_nutrition, _, _ = model(images)

        loss = (
            GROWTH_LOSS_WEIGHT * loss_fn(logits_growth, growth_labels)
            + NUTRITION_LOSS_WEIGHT * loss_fn(logits_nutrition, nutrition_labels)
        )
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        n_batches += 1
        growth_correct += (logits_growth.argmax(1) == growth_labels).sum().item()
        nutrition_correct += (logits_nutrition.argmax(1) == nutrition_labels).sum().item()
        total += images.size(0)

    return {
        "loss": total_loss / n_batches,
        "growth_acc": growth_correct / total,
        "nutrition_acc": nutrition_correct / total,
    }


@torch.no_grad()
def evaluate(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
) -> dict[str, float]:
    model.eval()
    total_loss = 0.0
    n_batches = 0
    growth_correct = 0
    nutrition_correct = 0
    total = 0

    loss_fn = nn.CrossEntropyLoss()

    for batch in loader:
        images, growth_labels, nutrition_labels = batch
        images = images.to(device)
        growth_labels = growth_labels.to(device)
        nutrition_labels = nutrition_labels.to(device)

        logits_growth, logits_nutrition, _, _ = model(images)
        loss = (
            GROWTH_LOSS_WEIGHT * loss_fn(logits_growth, growth_labels)
            + NUTRITION_LOSS_WEIGHT * loss_fn(logits_nutrition, nutrition_labels)
        )
        total_loss += loss.item()
        n_batches += 1
        growth_correct += (logits_growth.argmax(1) == growth_labels).sum().item()
        nutrition_correct += (logits_nutrition.argmax(1) == nutrition_labels).sum().item()
        total += images.size(0)

    return {
        "loss": total_loss / n_batches,
        "growth_acc": growth_correct / total,
        "nutrition_acc": nutrition_correct / total,
    }


# ---------------------------------------------------------------------------
# Checkpointing
# ---------------------------------------------------------------------------


def save_checkpoint(model: nn.Module, checkpoint_path: Path) -> None:
    checkpoint_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(
        {
            "model_state_dict": model.state_dict(),
            "model_class": "DualHeadClassifier",
            "image_size": IMAGE_SIZE,
        },
        checkpoint_path,
    )
    logger.info("checkpoint.saved", extra={"path": str(checkpoint_path)})


def load_checkpoint(checkpoint_path: Path) -> DualHeadClassifier:
    """Load a trained checkpoint, returning a DualHeadClassifier instance."""
    ckpt = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    model = DualHeadClassifier(pretrained=False)
    model.load_state_dict(ckpt["model_state_dict"])
    return model


# ---------------------------------------------------------------------------
# Main training entry point
# ---------------------------------------------------------------------------


def main(
    data_dir: Path | str | None = None,
    checkpoint_path: Path | str | None = None,
    epochs: int = DEFAULT_EPOCHS,
    batch_size: int = DEFAULT_BATCH_SIZE,
    lr: float = DEFAULT_LR,
    device: str | None = None,
) -> DualHeadClassifier:
    """Train the dual-head classifier end-to-end."""

    # Resolve device
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    device = torch.device(device)
    print(f"[Layer 1b training] device = {device}")

    # Ensure training data exists
    if data_dir is None:
        from adoptakale.utils.config import DATA_DIR
        data_dir = DATA_DIR / "cv_training"
    else:
        data_dir = Path(data_dir)

    if not (data_dir / "manifest.json").exists():
        print(f"[Layer 1b] Training data not found at {data_dir}/ — generating synthetic data…")
        generate_training_data(output_dir=data_dir)

    manifest = load_training_data(output_dir=data_dir)
    train_ds = SyntheticCVDataset(manifest, split="train")
    val_ds = SyntheticCVDataset(manifest, split="val")

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=0)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=0)

    print(
        f"[Layer 1b] Training: {len(train_ds)} images | "
        f"Validation: {len(val_ds)} images | "
        f"Epochs: {epochs}"
    )

    # Build model
    model = DualHeadClassifier(pretrained=True)
    # Spec §3.2: frozen backbone for MVP — only train the task heads.
    for param in model.backbone.parameters():
        param.requires_grad = False
    model.to(device)

    optimizer = optim.AdamW(
        (p for n, p in model.named_parameters() if n.startswith("shared.") or n.startswith("head_")),
        lr=lr,
        weight_decay=0.01,
    )
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    # Resolve checkpoint path
    if checkpoint_path is None:
        checkpoint_path = MODELS_DIR / "layer1b_efficientnet_b0.pt"
    else:
        checkpoint_path = Path(checkpoint_path)
    checkpoint_path.parent.mkdir(parents=True, exist_ok=True)

    best_val_loss = float("inf")
    t0 = time.monotonic()

    for epoch in range(1, epochs + 1):
        train_metrics = train_epoch(model, train_loader, optimizer, device)
        val_metrics = evaluate(model, val_loader, device)
        scheduler.step()

        epoch_secs = time.monotonic() - t0
        logger.info(
            "train.epoch",
            extra={
                "epoch": epoch,
                "train_loss": round(train_metrics["loss"], 4),
                "train_growth_acc": round(train_metrics["growth_acc"], 3),
                "train_nutrition_acc": round(train_metrics["nutrition_acc"], 3),
                "val_loss": round(val_metrics["loss"], 4),
                "val_growth_acc": round(val_metrics["growth_acc"], 3),
                "val_nutrition_acc": round(val_metrics["nutrition_acc"], 3),
            },
        )
        print(
            f"Epoch {epoch:02d}/{epochs} | "
            f"train_loss={train_metrics['loss']:.4f} "
            f"growth_acc={train_metrics['growth_acc']:.1%} "
            f"nutrition_acc={train_metrics['nutrition_acc']:.1%} | "
            f"val_loss={val_metrics['loss']:.4f} "
            f"growth_acc={val_metrics['growth_acc']:.1%} "
            f"nutrition_acc={val_metrics['nutrition_acc']:.1%} | "
            f"{epoch_secs:.1f}s"
        )

        # Save best model
        if val_metrics["loss"] < best_val_loss:
            best_val_loss = val_metrics["loss"]
            save_checkpoint(model, checkpoint_path)
            print(f"  ↳ Best model saved → {checkpoint_path}")

    print(
        f"\n[Layer 1b training complete] "
        f"Best val_loss={best_val_loss:.4f} | "
        f"Checkpoint: {checkpoint_path}"
    )
    return model


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train Layer 1b dual-head classifier")
    parser.add_argument("--data-dir", type=str, default=None, help="Training data directory")
    parser.add_argument("--checkpoint", type=str, default=None, help="Checkpoint output path")
    parser.add_argument("--epochs", type=int, default=DEFAULT_EPOCHS)
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE)
    parser.add_argument("--lr", type=float, default=DEFAULT_LR)
    parser.add_argument("--device", type=str, default=None)
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(name)s %(message)s",
    )
    main(
        data_dir=args.data_dir,
        checkpoint_path=args.checkpoint,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        device=args.device,
    )
